### ISSUE TITLE
We need an option to hide the value of the transactions (in USD) 

### ISSUE THREAD

**Issue by vhoanghac** [harmony-one/explorer-v2-frontend#1]
Just like the old explorer. 

Somehow looking at the number of ONE is better for my emotion than its value in USD.

**Comment by vpcodebase** [comment]
Hi @vhoanghac , we will think about it)

**Comment by hypnagonia** [comment]
we'll add option to the build config, so you will be able to do your own build of the app with disabled fiat numbers
