### ISSUE TITLE
Harmony explorer front end showing incorrect blockspeeds

### ISSUE THREAD

**Issue by WellnessOne** [harmony-one/explorer-v2-frontend#108]
Problem noticed around 12/30/21 @ 11am PST. Shows incorrect values for shard 0 block speeds - see image below

![5E24C22D-FD99-4903-A868-783A635FADB0](https://user-images.githubusercontent.com/92875667/147782046-2f832c8e-6cc0-421e-8130-000fb1c1412d.jpeg)

**Comment by ArtemKolodko** [comment]
Issue caused by indexer lag, when it was about 8 hours out of sync
