### ISSUE TITLE
Harmony explorer returning blank hashs

### ISSUE THREAD

**Issue by WellnessOne** [harmony-one/explorer-v2-frontend#109]
Some community members have reported their transaction hashes returning as blank when searched on the harmony explorer. I am able to recreate that issue using chrome on mobile.

Example of a hash that appears blank:
https://explorer.harmony.one/tx/0x30bdbb31a79e61c76ff6e7a360be49c46fc9db7821021c3a10485eb1a12c89f1

**Comment by ArtemKolodko** [comment]
It seems that the problem was related to the indexer lag. Now the page from the example above is loading correctly.
