### ISSUE TITLE
Fail to verify contract

### ISSUE THREAD

**Issue by playsnook** [harmony-one/explorer-v2-frontend#114]
![image](https://user-images.githubusercontent.com/85632593/150010459-fdab27aa-c045-4495-9bba-5596cb2ace4e.png)

**Comment by victaphu** [comment]
Hi @playsnook can you try this again?

Btw, please refer to this set of information for verifying contracts:
https://victa-kwok-wai-phu.gitbook.io/harmony-contract-verification-service/tutorials/verifying-contracts-using-hardhat-and-harmony-explorer
