### ISSUE TITLE
[feature request] permission revoker / manager

### ISSUE THREAD

**Issue by purple5pumpkin235** [harmony-one/explorer-v2-frontend#126]
On Etherscan and Etherscan forks, it is very easy to check and revoke spend permissions.

https://etherscan.io/tokenapprovalchecker
https://arbiscan.io/tokenapprovalchecker
https://polygonscan.com/tokenapprovalchecker
https://ftmscan.com/tokenapprovalchecker
https://snowtrace.io/tokenapprovalchecker

This would be a nice feature to have on the Harmony explorer.

**Comment by climbcrypto** [comment]
I agree with purple. As there is more attention coming to harmony, surely there will be bad actors as well. For my mental health, having something like this would be much appreciated!

**Comment by OgreAbroad** [comment]
Yep.  This would 100% be an outstanding feature to build now… as it will likely become a standard later.

**Comment by victaphu** [comment]
Test cases for tool
https://docs.google.com/spreadsheets/d/1m-gCnwn46Lsz-3LjCdYJ5hEbxtBbQwTHQYafY2dTxUg/edit?usp=sharing

**Comment by victaphu** [comment]
Closing this issue as the Approval tool has been deployed into mainnet and testnet explorers. Thanks for raising this useful feature!
