### ISSUE TITLE
Conflicting `from` and `to` fields

### ISSUE THREAD

**Issue by sebastian-alpha** [harmony-one/explorer-v2-frontend#151]
In https://explorer.harmony.one/address/0xdcc7ef68517871fdb1962a0090dc9ac90384dbf7?activeTab=3, transaction `0xd74d035bae41c53d81ee48a725b134322c3ca9af159029504586b90b4f8fe4e5`

![image](https://user-images.githubusercontent.com/95600569/157848960-3722a9e9-62cb-41b9-bfd9-e66631fb664e.png)

Notice that the 'from` is Viper with address `0xea589e93ff18b1a1f1e9bac7ef3e86ab62addc79` and the `to` is to `0xdcc7ef68517871fdb1962a0090dc9ac90384dbf7`

Upon clicking on the specific transaction (https://explorer.harmony.one/tx/0xd74d035bae41c53d81ee48a725b134322c3ca9af159029504586b90b4f8fe4e5), the fields are now swapped.

![image](https://user-images.githubusercontent.com/95600569/157849140-b06b4100-881a-4d95-80a7-4e6ee6336d98.png)

**Comment by ArtemKolodko** [comment]
Checked txn with data from RPC:
```
curl --location --request POST 'https://api.s0.t.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "eth_getTransactionByHash",
    "params": ["0xd74d035bae41c53d81ee48a725b134322c3ca9af159029504586b90b4f8fe4e5"]
}' | grep "from"
```
from = 0xdcc7ef68517871fdb1962a0090dc9ac90384dbf7
to = 0xea589e93ff18b1a1f1e9bac7ef3e86ab62addc79 (Viper)

Transaction details show the correct data, will check HRC20 txs list
