### ISSUE TITLE
front end changes

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/explorer-v2-frontend#18]
- [x] only use https://harmony.one/brand fonts and color: nunito, grey not full black
- [x] remove price under logo (duplicate display)
- [x] have 4 siginficant digits for price
- [x] 2x size of logo
- [x] replace shard count by “transaction volume” (accumulated values of all transactions) like tx count
- [x] on the front page, remove the little box “copy” icons under “latest transaction” on the top pages. it is cluttering up the front page. you can keep those on the txn detail pages.

**Comment by vpcodebase** [comment]
@lijiang2087 Done
