### ISSUE TITLE
Internal tab - Pagination bug

### ISSUE THREAD

**Issue by gerry05** [harmony-one/explorer-v2-frontend#188]
Latest transactions in the **10/25/50** Records per page is not showing in the first page.

https://user-images.githubusercontent.com/26299783/170150770-c9a61eec-42ea-4ae6-b9b6-9512a398fc85.mp4

You will see at the video below that the transaction **timestamp 05/25/2022**  is visible at the page 6 while the transactions at the page 1-5 are older.

https://user-images.githubusercontent.com/26299783/170151000-06d3da2d-2a91-44c4-b920-8398d49b989d.mp4

**Comment by ArtemKolodko** [comment]
Found an issue on backend in results ordering, will be fixed in this PR: 
https://github.com/harmony-one/explorer-v2-backend/pull/61

**Comment by ArtemKolodko** [comment]
@gerry05 issue should be fixed now
