### ISSUE TITLE
Enhancement "Nice to haves" Checklist

### ISSUE THREAD

**Issue by dirtycajunrice** [harmony-one/explorer-v2-frontend#192]
These are all improvements that are not a current bug, but would enhance user experience
- [x] URI-routed pagination - let a user skip to page 45 without having to click the arrow button 44 times
- [x] Filter by address - Allow viewing a subset of transactions of a tab filtered by address

Will expand on this list as things come up

**Comment by ArtemKolodko** [comment]
PR #194 is for first proposed improvement: URI-router pagination. And added First and Last page buttons, pagination UI improved

**Comment by ArtemKolodko** [comment]
PR #212 Added filter by address
