### ISSUE TITLE
Replace Burger Icon (top right) with Gear Icon 

### ISSUE THREAD

**Issue by Dewansahil** [harmony-one/explorer-v2-frontend#24]
<img width="1416" alt="Screen Shot 2021-07-07 at 10 13 51 AM" src="https://user-images.githubusercontent.com/45057123/124801744-087ddd00-df0c-11eb-9b13-a3f587c9d5cc.png">

**Comment by hypnagonia** [comment]
we didnt find suitable settings icon in the standard icon pack, will pick an external one..
