### ISSUE TITLE
Only most recent 100 transactions are shown

### ISSUE THREAD

**Issue by BK4230** [harmony-one/explorer-v2-frontend#28]
Hi there,

I'm only able to see the last 100 transactions when I search my wallet address in the explorer (regardless of the records per page which I select). When I click the right arrow at the bottom, it says there's 'no data to display.' Not sure if this is a problem for others, but if so would you please try to fix this or advise what I'm doing wrong.

Thanks

**Comment by hypnagonia** [comment]
related txs limited to 100. this is temporary trade-off. we will increase the limit in some future

**Comment by ArtemKolodko** [comment]
Fixed, supported up to 100K related transactions
