### ISSUE TITLE
Transaction history popup position

### ISSUE THREAD

**Issue by Johan22** [harmony-one/explorer-v2-frontend#3]
Hello,

There is a small issue/improvement with the popup on the transaction history.
Right now the popup overlaps the graph, and so it is complicated to see the details for an other day.
Can we just display the popup just above the graph? 
Thank you!

![image](https://user-images.githubusercontent.com/13732043/123694986-03dc6900-d828-11eb-9e9c-3a2c60983a4a.png)

**Comment by vpcodebase** [comment]
@Johan22 Hi, we are research this question

**Comment by ArtemKolodko** [comment]
Seems fixed with updated charts
