### ISSUE TITLE
Transaction page gasPrice, gasLimit and transaction cost

### ISSUE THREAD

**Issue by michaelotis** [harmony-one/explorer-v2-frontend#31]
Transaction page should show gasPrice in Gwei denomination and ordered on the transaction page:

Gas Limit
Gas Price
Transaction Fee / Cost

As to allow someone to easily see the multiplication of the first two fields into the last field.

**Comment by hypnagonia** [comment]
currently waiting for Alex to deliver new GetReceiptsByBlockHash RPC method

**Comment by AlexiaChen** [comment]
@hypnagonia @sophoah actually PR is created， https://github.com/harmony-one/harmony/pull/3826
