### ISSUE TITLE
Pagination on HRC20 tab not working

### ISSUE THREAD

**Issue by Severino** [harmony-one/explorer-v2-frontend#50]
## What is happening?

When visiting the HRC20 tab, only the first page of transactions is visible.
Pagination does not work.
However, you can see there are more txs by increasing the page limit to 100.

## Expected Behaviour

Pagination should work for HRC20 tokens

## Example
https://explorer.harmony.one/address/0xeb8fc2c39b8145b0860abda0df987719cbad29ca?activeTab=3

**Comment by ArtemKolodko** [comment]
Pagination for erc20 tokens was released on mainnet. Currently supported up to 100.000 total records for address.
