### ISSUE TITLE
Read Contract: Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/explorer-v2-frontend#54]
The Read Contract feature seems incomplete or at least produces errors like:
```
Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
```
For example, check the published contract: https://explorer.harmony.one/address/0xcf664087a5bb0237a0bad6742852ec6c8d69a27a?activeTab=7

<img width="1360" alt="Screen Shot 2021-08-04 at 11 25 19 AM" src="https://user-images.githubusercontent.com/13854340/128234756-47ecdc44-14a4-4fcd-bab6-0fafbeeecc69.png">

**Comment by potvik** [comment]
Fixed
