### ISSUE TITLE
Renounce Ownership Issue

### ISSUE THREAD

**Issue by MakiMoon** [harmony-one/explorer-v2-frontend#59]
Go to explorer 
->
Go to contract
->
Go to write contract 
-> renounce ownership transaction appears in metamask
-> if confirmed - contract is renounced within 2 seconds

**Comment by MakiMoon** [comment]
https://explorer.harmony.one/address/0x86dd7ad4e6fe09e4a5445cc2c9acd729bedb95ed

**Comment by MakiMoon** [comment]
renounced ownership was confirmed and sent to dead address 0x0000....

**Comment by potvik** [comment]
Fixed
