### ISSUE TITLE
Deployed HRC721 appears as contract and not HRC721 on explorer

### ISSUE THREAD

**Issue by lootblocks** [harmony-one/explorer-v2-frontend#61]
Name, Symbol, total supply, inventory (all the good HRC721 stuff) not appearing.

https://explorer.harmony.one/address/0x9e8160b2ccb5335bc4183277e46e87d97fe49542?activeTab=0

**Comment by ArtemKolodko** [comment]
the contract **0x9e8160b2ccb5335bc4183277e46e87d97fe49542** does not have the required methods for HRC721:
totalSupply, ownerOf, tokenURI, transferFrom, safeTransferFrom

Can be checked with tool:
https://explorer.harmony.one/tools/checkHrc?address=0x9e8160b2ccb5335bc4183277e46e87d97fe49542
wait for loaded bytecode, switch to HRC721

**Comment by ArtemKolodko** [comment]
Closing issue
