### ISSUE TITLE
Explorer contract page: some write methods not working

### ISSUE THREAD

**Issue by potvik** [harmony-one/explorer-v2-frontend#62]
Explorer contract page: some write methods not working

https://explorer.harmony.one/address/0xd81c20ca3d9501cadbf861135c516e3d0ea599d6?activeTab=7

sentPrice method not working

![image](https://user-images.githubusercontent.com/57394565/129216259-aee7c448-6148-42d3-bc95-e62f00c4c58e.png)

**Comment by ArtemKolodko** [comment]
Checked, issue fixed
