### ISSUE TITLE
Display inline HRC1155 images in Explorer

### ISSUE THREAD

**Issue by givp** [harmony-one/explorer-v2-frontend#66]
Similar to [Etherscan](https://etherscan.io/tx/0xeeaa347e1ac61e144ec83c2e50c00409011b24e5c99b624d39a1dbe8fa6b5897) we should show a thumbnail of the NFT in Explorer.

![image](https://user-images.githubusercontent.com/205550/132905733-15545b27-a76d-44b7-b105-89ae4b53e981.png)

**Comment by hypnagonia** [comment]
![telegram-cloud-document-2-5334571087843824324](https://user-images.githubusercontent.com/4476992/133265051-c14b9d64-fb37-464b-b504-770648ba1eb9.jpg)
done
