### ISSUE TITLE
harmony explorer doesn't show outbound transactions from harmony gnosis multisig

### ISSUE THREAD

**Issue by lijiang2087** [harmony-one/explorer-v2-frontend#72]
here are the txn hashes:

1. https://explorer.harmony.one/tx/0x0cdb5a8142f148ec7e955795901cf19665802c77c9f126b705c6079891dba5d6
2. https://explorer.harmony.one/tx/0x51c9b0c5eb37a1b8dba201a8efb6a6d6bab36eaa8ce7f11b77a6c4a6693600a7
3. https://explorer.harmony.one/tx/0xf7c27f0340cfd0ba7099e524c673790f8a644e54dd4a663c8fdf50db93c0be3d
4. https://explorer.harmony.one/tx/0x108de35ec308787ab78b73d229828020d5eb59e68582b3c278660dd4248b0373
5. https://explorer.harmony.one/tx/0x44a4e2099dc8bd5cc170b4cab7678d61f3751389edc4d70e7260557c0b4cf36f

those show 0 value on the explorer, but they had 1 ONEs

**Comment by sophoah** [comment]
@hypnagonia could you have a look ? seems to be a rouding issue

**Comment by ArtemKolodko** [comment]
Update: feature is available for all new transactions since April 8

- added new button "Show internal" next to "0 ONE" in txs list
- button is available only if transactions containers internal transfers
