### ISSUE TITLE
Explorer displayed incorrect WONE in wallets

### ISSUE THREAD

**Issue by MicahBly** [harmony-one/explorer-v2-frontend#75]
WHAT HAPPENS:
Many users report seeing WONE in varying quantities in their wallet.

HOW TO REPRODUCE:
Goto any wallet in the Explorer, it may say it contains WONE, but if you check the WONE Explorer holders page https://explorer.harmony.one/address/0xcf664087a5bb0237a0bad6742852ec6c8d69a27a?activeTab=5
it says that they have none. This is also supported by connecting to any dex or adding the contract code to metamask.

**Comment by twobitEDD** [comment]
A discord user reported "phantom $WONE" showing up in their wallet, they did have a history of this transaction but it could've been withdrawn from an LP token they used.
https://discord.com/channels/532383335348043777/712401237777317888/907519829920063508

When they check the explorer, the money shows up, when they check their wallet, the funds are missing.
![image](https://user-images.githubusercontent.com/2461243/140897220-55e586ba-0daa-4021-b70c-c3b33753e6f7.png)

![image](https://user-images.githubusercontent.com/2461243/140897271-5b61cf0b-6a64-45e6-b5e2-949ce4cd68d3.png)
![image](https://user-images.githubusercontent.com/2461243/140897372-4219a16d-b40a-4d3f-82c4-c7d5d1648b7a.png)
With the correct WONE contract
![image](https://user-images.githubusercontent.com/2461243/140897520-8503eda7-58a7-4ef8-8b24-45e0197f2a6b.png)
 
Their wallet address:
https://explorer.harmony.one/address/0xc25e4d9c5de4bdf7d0b940debe45d02f654a5bce

**Comment by ArtemKolodko** [comment]
Issue should be solved since #145  is merged - erc20 balances is are requested from RPC
