### ISSUE TITLE
Bug [Firefox]: Transactions table labels overlap with from address

### ISSUE THREAD

**Issue by agileurbanite** [harmony-one/explorer-v2-frontend#80]
Bug [Firefox]: Transactions table labels overlap with from address

![Screen Shot 2021-10-22 at 12 08 56 PM](https://user-images.githubusercontent.com/2501324/138510233-9dbde63e-213b-4a07-b4e1-7c8ed36b62a6.png)

**Comment by ArtemKolodko** [comment]
Fixed in [https://github.com/harmony-one/explorer-v2-frontend/commit/7089ea8a26b1b240feb0b19de0cce072fe2d6ca3#diff-3b5cea8fd7d6718d042f94c576d5370f4b29e35d42c8537d9caa2420da2aea05R243](commit). Checked on Firefox for Mac.
