### ISSUE TITLE
Testnet frontend is not in sync with the main branch

### ISSUE THREAD

**Issue by sophoah** [harmony-one/explorer-v2-frontend#90]

**Comment by mirrormirage0** [comment]
synced testnet FE with mainnet main branch

**Comment by ArtemKolodko** [comment]
Added different testnet .env:
[https://github.com/harmony-one/explorer-v2-frontend/commit/cdded1324d765fa4574b5243111e88f489087fa7
test](https://github.com/harmony-one/explorer-v2-frontend/commit/cdded1324d765fa4574b5243111e88f489087fa7
test)
testnet explorer was updated, issue closed
