### ISSUE TITLE
Add aUST to explorer

### ISSUE THREAD

**Issue by jacksteroo** [harmony-one/explorer-v2-frontend#94]
Please add aUST to be recognized in Harmony's explorer views

The first test bridge transaction completed
- https://explorer.harmony.one/tx/0x20245896488f904068533f07f0d326160d8b1222a75ee688060b7bc0c47355cf?activeTab=0
- https://finder.terra.money/mainnet/tx/8C781FEF673D7B71C242BED3A9E8620C63F226BE3DC45BF3A4CE5BF0B019AD5E

**Comment by hypnagonia** [comment]
resolved. just needed some time for explorer to track new tokens and prune old cache
