### ISSUE TITLE
Explorer page crashes

### ISSUE THREAD

**Issue by potvik** [harmony-one/explorer-v2-frontend#99]
https://explorer.harmony.one/address/0x723f3c70a60191c52457e9802f5ec03b96302dd8

![image](https://user-images.githubusercontent.com/57394565/144727438-de9df1ee-05e7-4623-bb6b-3f6bdd76eef9.png)

**Comment by xiaoyu2006** [comment]
I came from the forum. Here's another screenshot.

<img width="1792" alt="截屏2021-12-14 下午8 15 34" src="https://user-images.githubusercontent.com/32544798/145996608-2ba9b42f-a5b8-46a0-88c3-959154020970.png">

**Comment by xiaoyu2006** [comment]
@hypnagonia Any updates? It really affects user experiences.

**Comment by Zil-B** [comment]
I've had different errors than above, but seems to all result in the same white screen crash.

![image](https://user-images.githubusercontent.com/84344709/146656772-bbd65544-4adf-417d-9145-8b694225f969.png)

**Comment by Zil-B** [comment]
The explorer stores an insane amount of data in local storage which seems to be related to this issue. 

Looks like it tries to fetch all ERC20s / ERC721s & more data to set in local storage - can this not be moved elsewhere? (e.g. redux)

**Comment by xiaoyu2006** [comment]
> I've had an additional different error than above, but seems to all result in the same white screen crash.

I have set breakpoints and it turned out it’s the TypeError bug that caused the white screen.

**Comment by hypnagonia** [comment]
should be fixed by now
